services:
  app:
     image: ghcr.io/hn721/fgo24-be-tickitz:latest
     ports:
      - 9203:8080
     volumes:
      - data_uploads:/uploads
     networks:
      - netapp
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=721
    volumes:
      - data_postgres:/var/lib/postgresql/data
      # - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - netapp
  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
  data_uploads:
networks:
  netapp: